version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: charge-ch
    restart: always
    command: npm start
    environment:
      - MONGO_URL=mongodb://mongo:27017/kanastra-boleto-charge
    volumes:
      - ./dist:/usr/src/charge-ch/dist
    ports:
      - "5050:5050"
    links:
      - mongo